# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js
    - nodejs_version: "7"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run patch

test_script:
  - node --version
  - npm --version
  - npm test

build: off

version: "{build}"
